### ISSUE TITLE
 BinaryTraits.jl

### ISSUE THREAD

**Issue by AriMKatz** [zenna/AndTraits.jl#1]
https://github.com/tk3369/BinaryTraits.jl

Have you seen it? Seems to do everything you want, unless I missed something on a cursory comparison.

Also has interfaces and checking.

**Comment by zenna** [comment]
I don't see a conjunctive example on the website.  Can you show me one?  This package was just an extraction of this issue https://github.com/tk3369/BinaryTraits.jl/pull/49 (which you were part of)

**Comment by AriMKatz** [comment]
Heh, I forgot about that. I thought BinaryTraits could do dispatch on conjuctive traits, but I guess not.
